import 'package:alibali/PageQuestion/CLassUtilisee.dart';


   // la table de sous questions biologie
List<Quizx>sousQuestionBiologie=[
    Quizx(1, "Quelle est la capitale du Qatar ? ", ["Abu Dhabi","Amman","Doha","Dubaï","A.B.R"],"Doha"," Amman est la capitale de la Jordanie; Abu Dhabi et Dubaï sont des capitales d’émirats des Émirats arabes unis."),
    Quizx(1, "Lequel de ces États ne fait pas partie de l’Union européenne ?  ", ["Croatie","Lituanie","Malte","Norvège","A.B.R"],"Norvège"," La procédure d’adhésion de la Norvège à l’Union européenne est une des trois procédures (avec celles de la Suisse et de l’Islande) qui n’ont pas abouti. Par deux fois, en 1972 et 1994 et par voie référendaire, le peuple norvégien a refusé l’adhésion du pays à l’Union européenne. "),
    Quizx(1, "En France, quelle institution certifie les comptes de l’État ?", ["La Cour de cassation","La Cour des comptes","Le Conseil constitutionnel","Le Conseil d’État","A.B.R"], "La Cour des comptes"," Explication non disponible"), 
    Quizx(1, "En France, un projet de loi est une initiative législative :? ", ["gouvernementale inscrite à l’ordre du jour du Parlement","gouvernementale qui génère automatiquement un référendum populaire","parlementaire inscrite à l’ordre du jour du Parlement","parlementaire qui entraîne systématiquement la réunion du Parlement en congrès à Versailles","A.B.R"],"gouvernementale inscrite à l’ordre du jour du Parlement","Explication non disponiple"),
    Quizx(1, "En France, quel événement historique célèbre-t-on le 11 novembre? ", ["l’armistice de la Première Guerre mondiale","l’armistice de la Seconde Guerre mondiale","l’institution de la Communauté économique européenne","le débarquement allié sur les plages de Normandie","A.B.R"],"l’armistice de la Première Guerre mondiale"," La fin des combats de la Première Guerre mondiale (1914-1918) est marquée par la signature de l’armistice, le 11 novembre 1918. "),
    Quizx(1, "Quel président américain a démissionné après le scandale du Watergate en 1974?  ", ["Dwight D. Eisenhower","George H. W. Bush","Gerald Ford","Richard Nixon","A.B.R"],"Richard Nixon","Le scandale du Watergate est une affaire d’espionnage politique qui aboutit, en 1974, à la démission du président des États-Unis Richard Nixon. Pendant la campagne pour les élections présidentielles de 1972, cinq hommes sont arrêtés en train d’« inspecter » dans les locaux du parti démocrate, l’immeuble Watergate à Washington. Deux journalistes du Washington Post ont démontré, avec l’aide d’un mystérieux informateur connu sous le nom de Deep Throat («Gorge profonde»), qu’il existait des liens entre ces cambrioleurs et la présidence des ÉtatsUnis. Leurs enquêtes conduiront à l’inculpation de cinq collaborateurs de Richard Nixon, puis à la création, en février 1973, d’une commission d’enquête sénatoriale. Accusé d’avoir entravé l’action de la justice, Nixon sera contraint de démissionner (août 1974)"),
    Quizx(1, "La convention internationale, dénommée «protocole de Kyoto», est un accord:? ", ["destiné à relancer la croissance dans le monde après la crise économique et financière de 1929","mettant fin à la guerre de Corée","prévoyant la capitulation de l’armée japonaise à la fin de la Seconde Guerre mondiale","visant la réduction des émissions de gaz à effet de serre","A.B.R"],"visant la réduction des émissions de gaz à effet de serre","Le protocole de Kyoto est un accord international signé le 11 décembre 1997 à Kyoto, au Japon et entré en vigueur le 16 février 2005. Il visait à réduire, entre 2008 et 2012, d’au moins 5% par rapport au niveau de 1990 les émissions de six gaz à effet de serre:dioxyde de carbone, méthane, protoxyde d’azote et trois substituts des chlorofluorocarbones"),
    Quizx(1, "Laquelle des inventions suivantes doit-on à Alfred Nobel ?", ["la dynamite","la machine à vapeur","l’électricité","le téléphone","A.BN.R"],"la dynamite","Explication non disponible"),
    Quizx(1, "Qui a peint le tableau intitulé Guernica ? ",["Salvador Dalí","Francisco de Goya","Henri Matisse","Pablo Picasso","A.B.R"],"Pablo Picasso"," Le 1er mai 1937, des bombardiers nazis appelés par Franco ont détruit la ville de Guernica, faisant 1600 morts. Picasso peignit cette toile quelques mois plus tard."),
    Quizx(1, "Qui est le réalisateur du film Avatar (2009) ?", ["George Lucas","James Cameron","Luc Besson","Ron Howard","A.B.R"],"James Cameron","Explication non disponible"),
    Quizx(1,"La mode de reprodution de l'amibe est: ?", ["La bipartition","le bouturage","le bulbe","la schizogonie","la sporulation"],"La bipartition",""),
    Quizx(2,"Au cours de la méiose, le clivage des centromères s'effectue à ?: ", ["L'interphase","La prophase 1","La métaphase 1","L'anaphase 1","L'anaphase 2"],"L'anaphase 2",""),
    Quizx(3,"Un certain nombre des critères interviennent dans la classification des espèces animales ou végétales. la taille, la couleur, la forme ... constituent un critère: ?", ["Chimique","Cytologique","Descendance","Morphologique","Scientifique"],"Morphologique",""),
    Quizx(5,"l'ensemble des gènes d'un individu est appelé ?:", ["Clone","Génotype","Hybride","Phénotype","Génome"],"Génome",""),
    Quizx(6,"indiquez la théorie de l'évolution qui stipule que les espèces n'ont Pas changé jusqu'à nos jours", ["La génération spontanée","Le créationnisme","Le fixisme","Le mutationnisme","Le lamarckisme"],"Le fixisme",""),
    Quizx(8,"L'ensemble des  chromosomes morphologiquement differents d'une cellules est :?",["Clone","Génotype","Hybride","Phénotype","Génome"],"Génome",""),
    Quizx(7,"La  periode de l'ère primere ou sont apparues les gymnospermes est : ?", ["Le cambrien","Le carbonifère","Le devonien","Le permien","Le silurien"],"Le permien",""),
    Quizx(7,"La fatigue musculaire est due à la carence en :  ?", ["lode","magnésium","calcium","chlorure de sodium","litium"],"calcium",""),
    Quizx(7,"Indiquez la proposition qui désigne le développement de l'œuf sans fécondation: ?", ["Clone ","FIV","Parthénogenèse","Hermaphrodite","OGM"],"Parthénogenèse",""),
    Quizx(7,"chacun de grands milieux de la planete s'appelle: ?", ["l'ecotone","l'ecotope","l'ecotype","la biosphere","le biome"],"l'ecotype",""),
    Quizx(7,"L'hormone qui assure le controle de la spermatogénèse est: ?", ["la testostérone","La progestérone","La F.S.H","La prolactine","Landrostérone"],"la testostérone",""),
    Quizx(7,"chacun de grands milieux de la planete s'appelle: ?", ["l'ecotone","l'ecotope","l'ecotype","la biosphere","le biome"],"l'ecotype",""),


    Quizx(1, " Parmi ces quatre pièces de théâtre, laquelle n’a pas été écrite par Molière ? ", ["Le Jeu de l’amour et du hasard","Le Malade imaginaire","Le Tartuffe","Les Femmes savantes","A.B.R"], "Le Jeu de l’amour et du hasard", "Le Jeu de l’amour et du hasard est une comédie en trois actes de Marivaux, représentée pour la première fois le 23 janvier 1730. "),
    Quizx(2, "Quelle est la capitale du Brésil ?", ["Brasilia","Rio de Janeiro","Salvador de Bahia","São Paulo","A.B.R"], "Brasilia",""),
    Quizx(3, "De ces quatre villes, laquelle est la plus orientale ? ",["Besançon","Lyon","Nancy","Nice","A.B.R"], "Nancy", "La partie orientale d’un espace est la partie la plus à l’est de ce territoire. "),
    Quizx(5, "Comment sont actuellement désignés les conseillers communautaires auprès des établissements publics de coopération intercommunale (EPCI) ? ", ["au suffrage universel direct","au suffrage universel indirect","par décision du président du conseil communautaire","par tirage au sort parmi les conseillers municipaux","A.B.R"], "au suffrage universel direct", " Les conseillers communautaires sont élus pour la même durée, selon le même mode de scrutin que les conseillers municipaux et par un même vote. "),
    Quizx(6, "Quizx(6,  Le Chemin des Dames est une bataille de :?",["la guerre de Cent Ans","la guerre de 1870","la Première Guerre mondiale","la Seconde Guerre mondiale","A.B.R"], "la Première Guerre mondiale", "La bataille du Chemin des Dames se déroule dans l’Aisne pendant la Première Guerre mondiale le 16 avril 1917. Elle a été une tentative de rupture du front allemand entre Soissons et Reims vers Laon, sous les ordres du général Nivelle, qui a lancé son fameux : « L’heure est venue, confiance, courage et vive la France ! » "),
    Quizx(7, "La loi de séparation des Églises et de l’État a été adoptée en France en ?:", ["1805","1901","1905","1945","A.B.R"], "1905", ""),
    Quizx(9, "Quel est le point commun entre ces quatre personnalités: Geneviève De Gaulle Anthonioz, Marie Curie, Germaine Tillion, Sophie Berthelot", ["Elles ont été choisies pour entrer au Panthéon","Elles ont fait d’importantes découvertes scientifiques","Elles ont occupé un portefeuille ministériel","Elles se sont illustrées par des actes de résistance pendant la Seconde Guerre mondiale","A.B.R"], "Elles ont été choisies pour entrer au Panthéon", ""),
    Quizx(11, " Que signifie l’abréviation « Cedex » ? ", ["courrier d’entreprise à distribution exceptionnelle","courrier entre départements exclus","courrier envoyé aux départements en exclusivité","courrier exceptionnel distribué en express","A.B.R"], "courrier d’entreprise à distribution exceptionnelle", ""),
    Quizx(12, "Dans la série américaine « 24 heures chrono », quel est le nom du personnage principal ? ", ["Jack Bauer","Jack Ryan","Jack Sparrow","Jack Reachel","A.B.R"], "Jack Bauer", ""),
    Quizx(5, " Parmi ces sites, inscrits au patrimoine mondial de l’Unesco, lequel abrite un mausolée ? ", ["le Taj Mahal","l’Alhambra","Persépolis","Pergame","A.B.R"], "le Taj Mahal", " Le Taj Mahal fut élevé de 1631 à 1641 près d’Agra en Inde par l’empereur Chah Djahan pour célébrer la mémoire de son épouse. "),
    Quizx(7, " Lequel de ces pays n’a pas de façade maritime avec la mer Noire ? ", ["la Bulgarie","la Géorgie","l’Albanie","l’Ukraine ","A.B.R"], "l’Albanie", ""),
    Quizx(8, "Quelle institution vérifie la validité des candidatures présidentielles ? ", ["l’Assemblée nationale","le Sénat","la Cour des comptesle","Conseil constitutionnel","A.B.R"], "Conseil constitutionnel", ""),
    Quizx(10, "Quelle était à l’origine la fonction de Facebook ?", ["un site de rencontres","un réseau social pour cuisinier","un album photo en ligne","un réseau social estudiantin","A.B.R"], "un réseau social estudiantin", ""),
    Quizx(12, "Combien de temps faut-il à la Terre pour faire le tour du Soleil ? ", ["une journée","28 jours","un an","dix ans","A.B.R"], "un an", ""),
    Quizx(16, "Lequel de ces termes n’appartient pas au monde du théâtre ? ", ["le quatrième mur","côté jardin","l’œil du prince","le bout à bout","A.B.R"], "le bout à bout", "Au théâtre, le quatrième mur désigne un « mur » imaginaire situé sur le devant de la scène, séparant la scène des spectateurs et « au travers » duquel ceux-ci voient les acteurs jouer. Dans le vocabulaire théâtral, le côté cour est le côté droit de la scène, vu de la salle, par opposition au côté jardin, qui est le côté gauche. L’œil du prince est l’angle de vue permettant de visualiser la perspective du décor sans déformation"),
    Quizx(17, " Mars est également appelée la « planète rouge » en raison ?:",["d’une illusion d’optique due à la chaleur du sol","de la présence d’oxyde de fer dans le sol","de la présence de diazote dans son atmosphère","de la lave en fusion présente à la surface","A.B.R"],"de la présence d’oxyde de fer dans le sol", ""),
    Quizx(19, " Figure emblématique de la philosophie des Lumières, François-Marie Arouet est également appelé: ", ["Diderot","Voltaire","Montesquieu","Rousseau","A.B.R"], "Voltaire", "")


];

